apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
  labels:
    app: pod-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-b
  template:
    metadata:
      labels:
        app: pod-b
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: b
spec:
  selector:
    app: pod-b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
